pkgs:
  name:
    - httpd
  state: present
fwd_svc:
  httpd:
    name: http
    state: enabled
    perm: yes
    now: yes
storage:
  partitions:
    - number: 1
      start: 1MiB
      end: 1000MiB
      device: /dev/sdb
      state: present
  volume_groups:
    - name: apache-vg
      device: /dev/sdb1
  logical_volumes:
    - name: www-lv
      size: 500M
      vgroup: apache-vg
      mount_path: /srv/www
      fs: xfs
apache:
  docroot: /srv/www/html
